module.exports = {
    plugins: ["unicorn"],
    rules: {
        "unicorn/custom-error-definition": "error",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-instanceof-array": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-for-loop": "error",
        "unicorn/no-hex-escape": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unsafe-regex": "error",
        "unicorn/no-unused-properties": "error",
        "unicorn/no-zero-fractions": "error",
        "unicorn/prefer-add-event-listener": "error",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-query-selector": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-type-error": "error",
        "unicorn/better-regex": "error",
        "unicorn/throw-new-error": "error",
        "unicorn/consistent-function-scoping": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-dom-node-dataset": "error",
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-negative-index": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-number-properties": "error",
        "unicorn/no-null": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/explicit-length-check": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-ternary": "error",
        "unicorn/numeric-separators-style": "error",
        "unicorn/catch-error-name": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/no-new-array": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/consistent-destructuring": "error",
        "unicorn/no-array-push-push": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-switch": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-module": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/require-array-join-separator": "error",
        "unicorn/require-number-to-fixed-digits-argument": "error",
        "unicorn/filename-case": [
            "error",
            { "cases": { "kebabCase": true, "camelCase": true, "pascalCase": true } }
        ],
        "unicorn/import-index": ["error", { "ignoreImports": true }],
        "unicorn/prevent-abbreviations": [
            "error",
            {
                "allowList": {
                    "args": true,
                    "props": true
                },
                "checkShorthandProperties": true
            }
        ],
    }
};